# Generated by Django 4.1 on 2022-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo_carrera', models.CharField(max_length=40)),
                ('plan_de_estudio', models.IntegerField()),
                ('resolucion_rectoral', models.CharField(max_length=20)),
                ('cantidad_asignaturas', models.IntegerField()),
                ('asignaturas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.CharField(max_length=40)),
            ],
        ),
    ]
